project:
  type: website
  output-dir: docs

website:
  title: "Documentacion de Sesiones Linux con Quarto, Hilos y Procesos en C"

  navbar:
    left:
      - href: index.qmd
        text: Inicio

      - href: arquitectura.qmd
        text: Arquitectura

      - href: evidencias.qmd
        text: Evidencias

      - href: resultados.qmd
        text: Resultados

      - href: codigo/sesion.html
        text: Sesión Generada

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



