---
title: "ShellDoc Web"
---

## Integrantes

- Karen Grefa
- Steven Arauz
- Geovanni Casa

## Descripción

ShellDoc Web es una herramienta desarrollada en lenguaje C que permite documentar automáticamente sesiones Linux utilizando procesos (`fork()`), hilos (`pthread`) y generación de documentación con Quarto.

##Objetivo General

Desarrollar una herramienta en lenguaje C capaz de documentar automáticamente sesiones Linux, registrando comandos y resultados para generar documentación web mediante Quarto.

##Objetivos Específicos
- Ejecutar comandos Linux utilizando procesos creados con fork().
- Capturar automáticamente la salida de los comandos mediante pipes y redirección de flujo.
- Implementar hilos (pthread) para registrar concurrentemente la información generada.
- Generar documentación automática en formato Quarto (.qmd) a partir de la sesión capturada.
- Convertir la documentación a HTML y publicarla mediante GitHub Pages.

## Tecnologías Utilizadas

- Linux
- Lenguaje C
- fork()
- pthread
- Mutex
- Quarto
- GitHub Pages

## Funcionalidades

- Ejecución de comandos Linux.
- Captura automática de resultados.
- Procesamiento concurrente mediante hilos.
- Generación de archivos `.qmd`.
- Conversión automática a HTML.
- Publicación web mediante GitHub Pages.

## Navegación

Utilice el menú superior para acceder a:

- Arquitectura
- Evidencias
- Resultados
- Sesión Generada
